site_name: DR.Murillo

theme:
  name: mkdocs
  locale: en
  color_mode: dark
  user_color_mode_toggle: true
  static_templates:
    - sitemap.html
  include_sidebar: false
extra_css:
  - css/custom.css